---
title: "Data_analysis_lasso_cox_immune_maker"
author: "Hewenjun"
date: "2017/10/11"
output: html_document
---
###这是一份分析免疫Marker在临床预测的作用评价
###包含以下分析过程：

1.数据预处理

2.数据建模，筛选出影响癌和癌旁，预后（死亡，复发）的免疫Marker

####1.数据预处理
```{r}
setwd("/Users/hewenjun/hwj_data/Tian_meng_xin")
data1=read.csv(file ="免疫评分临床数据.csv",header = T,fileEncoding = "GBK" )
names(data1)
dim(data1)
str(data1)
#数据重铸不太会，只能用笨方法
lasso.logi=data1[,c(1:33)]
lasso.logi.T=data1[,c(1,seq(2,33,by=2))]
lasso.logi.P=data1[,c(1,seq(3,33,by=2))]
names(lasso.logi.P)=names(lasso.logi.T)
lasso.logi=rbind(lasso.logi.T,lasso.logi.P)
lasso.logi$T_or_P=c(rep(1,280),rep(0,280))
```
####2.数据建模
```{r}
library(glmnet)
#lasso logistic
x.logi=data.matrix(lasso.logi[,c(2:17)])
y.logi=as.matrix(lasso.logi$T_or_P)
fit.logi=glmnet(x.logi,y.logi,family = "binomial")
plot(fit.logi)
set.seed(456)
cv.fit.logi=cv.glmnet(x.logi,y.logi,family="binomial")
plot(cv.fit.logi)
cv.fit.logi$lambda.min
cv.fit.logi$lambda.1se
predict(cv.fit.logi,type='coefficients',s=cv.fit.logi$lambda.min)
plot(cv.fit.logi$glmnet.fit,xvar = "lambda")
abline(v=log(cv.fit.logi$lambda.min),lty=2)
##lasso cox
##死亡
x=data.matrix(data1[,c(seq(2,33,by=2))[-c(3,13)]])
y=cbind(time=data1$OS,status=data1$OS_status)
fit1=glmnet(x,y,family="cox")
plot(fit1)
set.seed(123)
cv.fit1=cv.glmnet(x,y,family="cox")
plot(cv.fit1)
cv.fit1$lambda.min
cv.fit1$lambda.1se
predict(cv.fit1,type='coefficients',s=cv.fit1$lambda.min)
plot(cv.fit1$glmnet.fit,xvar = "lambda")
abline(v=log(cv.fit1$lambda.min),lty=2)
##复发
x=data.matrix(data1[,c(seq(2,33,by=2))[-c(3,13)]])
y=cbind(time=data1$DFS,status=data1$DFS_status)
fit1=glmnet(x,y,family="cox")
plot(fit1)
set.seed(123)
cv.fit1=cv.glmnet(x,y,family="cox")
plot(cv.fit1)
cv.fit1$lambda.min
cv.fit1$lambda.1se
predict(cv.fit1,type='coefficients',s=cv.fit1$lambda.min)
plot(cv.fit1$glmnet.fit,xvar = "lambda")
abline(v=log(cv.fit1$lambda.min),lty=2)
```